FROM mdernst/ubuntu-for-cf-jdk8

LABEL MAINTAINER="w23xing@uwaterloo.ca"

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  binutils \
  build-essential \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  python3 \
  python3-pip \
  python-pip \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir lithium \
&& pip install --no-cache-dir subprocess32 lithium

RUN export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
